---
title: "Turtle KEGG analysis"
author: "Yuejiao"
date: "2025-06-16"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(clusterProfiler)
library("KEGGREST")
library(tidyverse)
library(stringr)
library(ggplot2)
library("pathview")
library(svglite)
```

## Load the kegg db

```{r}
cmy_kegg_df <- data.frame(cmy_id = names(keggConv("ncbi-geneid", "cmy")),
          ncbi_id = keggConv("ncbi-geneid", "cmy")) %>% 
  separate(.,ncbi_id, into = c("info", "ncbi_gid"), sep = ":") %>% 
  select(-info) 
```

## Load background gene_list

```{r}
gene_list <- read_tsv("Data/3_kegg_analysis/KEGG og2geneid/candidate_enricher_gene_info.txt", 
                      col_names = c("gene","ncbi_gid","info")) %>% 
  select(-info) %>% 
  mutate( ncbi_gid = as.character(ncbi_gid))
gene_input <- read_tsv("Data/3_kegg_analysis/KEGG og2geneid/candidate_enricher_og2gene.txt",
                       col_names = c("busco_id","gene"))
genes <- left_join(gene_input,gene_list, by = "gene") %>% 
  left_join(.,cmy_kegg_df, by = "ncbi_gid" ) %>% 
  filter(!is.na(cmy_id ))
```

## KEGG enrichment

### load outiler genes
```{r}
# 254 genes
outliers_dn <- read.csv("Results/1_mahalanobis_outliers/outliers_genes/dn_q95.csv", col.names = c("busco_id","pval")) %>% 
  left_join(.,genes, by = "busco_id") %>% 
  filter(!is.na(cmy_id )) %>% 
  select(ncbi_gid,cmy_id)
# 255 genes, converted 248 genes. 
outliers_ds <- read.csv("Results/1_mahalanobis_outliers/outliers_genes/ds_q95.csv", col.names = c("busco_id","pval")) %>% 
  left_join(.,genes, by = "busco_id") %>% 
  filter(!is.na(cmy_id )) %>% 
  select(ncbi_gid,cmy_id)
# 255 genes, converted 252 genes.
outliers_dnds <- read.csv("Results/1_mahalanobis_outliers/outliers_genes/dnds_q95.csv", col.names = c("busco_id","pval")) %>% 
  left_join(.,genes, by = "busco_id") %>% 
  filter(!is.na(cmy_id )) %>% 
  select(ncbi_gid,cmy_id)

# 255 genes, converted 254 genes.
outliers_pure <- read.csv("Results/1_mahalanobis_outliers/outliers_genes/raw_q95.csv", col.names = c("busco_id","pval")) %>% 
  left_join(.,genes, by = "busco_id") %>% 
  filter(!is.na(cmy_id )) %>% 
  select(ncbi_gid,cmy_id)

```

### enrich kegg function
```{r}
enrich_ref_kegg <- function(df){
  out_df <- enrichKEGG(gene = unique(df$ncbi_gid),
         pAdjustMethod = "fdr",
         organism = "cmy")
  out_df@result$Description <- sub(" - Chelonia mydas \\(green sea turtle\\)", "", out_df@result$Description)
  return(out_df)
}
```

### KEGG analysis
#### dN results
```{r}
kegg_ref_genes_dn <- enrich_ref_kegg(outliers_dn) ## 9 enriched terms

# Number of enriched terms
nrow(as.data.frame(kegg_ref_genes_dn))
```
#### dS results
```{r}
kegg_ref_genes_ds <- enrich_ref_kegg(outliers_ds)

# Number of enriched terms
nrow(as.data.frame(kegg_ref_genes_ds))
```
#### dN/dS results
```{r}
kegg_ref_genes_dnds <- enrich_ref_kegg(outliers_dnds) #8 enriched terms

# Number of enriched terms
nrow(as.data.frame(kegg_ref_genes_dnds))
```

#### visualize the pathway and highligh the outlier genes in red for dn/ds results
```{r}
desired_order <-  c("Spliceosome","Basal transcription factors", "mRNA surveillance pathway", "Proteasome", "RNA degradation", "Polycomb repressive complex","Viral life cycle - HIV-1","Cell cycle")
kegg_ref_genes_dnds@result$Description <- factor(kegg_ref_genes_dnds@result$Description,levels = desired_order)
KEGG_enriched_pathways <- dotplot(kegg_ref_genes_dnds, 
        x = "GeneRatio", 
        showCategory = length(desired_order)) + 
  scale_y_discrete(limits = rev(desired_order)) +
  scale_fill_gradientn(name = "Adjusted p-value", colours=c("#72315C", "#A6A867")) +
  #scale_size(name = "Gene count") +
  theme_minimal(base_family = "Arial") +
  labs(size="Gene count",
       x="Gene ratio") +
  theme(
    
    # base text (will cascade to anything not explicitly set below)
    text = element_text(
      family = "Arial", 
      color  = "black",
      size   = 14
    ),
    
    # axis titles and axis tick labels
    axis.title  = element_text(color = "black"),
    axis.text   = element_text(color = "black"),
    
    # legend title and labels
    legend.title = element_text(color = "black"),
    legend.text  = element_text(color = "black"),
    
    # strip text (for facets, if any)
    strip.text   = element_text(color = "black")
  )

## TODO: Arial

svglite('Results/KEGG_enriched_pathways.svg', width = 10, height = 4)
print(KEGG_enriched_pathways)
dev.off()

KEGG_enriched_pathways
ggsave("Results/KEGG_enriched_pathways.png", units = "in", height = 4, width = 6,
       dpi = 700)

#### write output enriched geneID
kegg_ref_genes_dnds@result %>% filter(p.adjust < 0.05) %>% select(geneID) %>% write_csv("Results/geneid.csv")
#### KEGG pathways 
kegg_path_id <- rownames(kegg_ref_genes_dnds@result %>% filter(p.adjust < 0.05) %>% select(ID))

for (i in kegg_path_id) {
  
  pathview(gene.data=outliers_dnds$ncbi_gid, 
         pathway.id=i, 
         species = "cmy")
}
```

#### pairwise distance results
```{r}
kegg_ref_genes_pure <- enrich_ref_kegg(outliers_pure) # 3
```
